### PR TITLE
 Modifying values to support data frame previews 

### PR DESCRIPTION
**Pull request by tpetricek**
Note that we first need to merge #136 and #137.

This is going to be fixing issue #124.

### CODE REVIEW

**Comment by nbarlowATI** [comment]
I had a go at merging this into develop, but ran into the following errors at runtime:
```
wrattler_client_1          | ERROR in ../src/languages/external.ts
wrattler_client_1          | Module not found: Error: Can't resolve '../common/lazy' in '/app/src/languages'
wrattler_client_1          |  @ ../src/languages/external.ts 47:13-38
wrattler_client_1          |  @ ../src/main.ts
wrattler_client_1          |  @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8080 ../node_modules/webpack/hot/dev-server.js ../src/main.ts
wrattler_client_1          | 
wrattler_client_1          | ERROR in /app/src/definitions/values.ts
wrattler_client_1          | [tsl] ERROR in /app/src/definitions/values.ts(8,25)
wrattler_client_1          |       TS2307: Cannot find module '../common/lazy'.
wrattler_client_1          | 
wrattler_client_1          | ERROR in /app/src/languages/external.ts
wrattler_client_1          | ../src/languages/external.ts
wrattler_client_1          | [tsl] ERROR in /app/src/languages/external.ts(10,25)
wrattler_client_1          |       TS2307: Cannot find module '../common/lazy'.
wrattler_client_1          | 
wrattler_client_1          | ERROR in /app/src/languages/javascript.ts
wrattler_client_1          | ../src/languages/javascript.ts
wrattler_client_1          | [tsl] ERROR in /app/src/languages/javascript.ts(170,17)
wrattler_client_1          |       TS2322: Type '{ kind: "dataframe"; url: string; data: any; }' is not assignable to type 'DataFrame'.
wrattler_client_1          |   Property 'preview' is missing in type '{ kind: "dataframe"; url: string; data: any; }'.
```
Is it possible there's something missing from this branch?

**Comment by nbarlowATI** [comment]
After merging the ```my/global-functions``` branch, the "common/lazy" errors don't appear, but still get
```
wrattler_client_1          | ERROR in /app/src/languages/javascript.ts
wrattler_client_1          | ../src/languages/javascript.ts
wrattler_client_1          | [tsl] ERROR in /app/src/languages/javascript.ts(170,17)
wrattler_client_1          |       TS2322: Type '{ kind: "dataframe"; url: string; data: any; }' is not assignable to type 'DataFrame'.
wrattler_client_1          |   Property 'preview' is missing in type '{ kind: "dataframe"; url: string; data: any; }'.
```
